language: bash

env:
  matrix:
    - TAG=5.3-apache
    - TAG=5.3-cli
    - TAG=5.3-fpm
    - TAG=5.4-apache
    - TAG=5.4-cli
    - TAG=5.4-fpm
    - TAG=5.5-apache
    - TAG=5.5-cli
    - TAG=5.5-fpm
    - TAG=5.6-apache
    - TAG=5.6-cli
    - TAG=5.6-fpm
    - TAG=6.0-apache
    - TAG=6.0-cli
    - TAG=7.0-apache
    - TAG=7.0-cli
    - TAG=7.0-fpm
    - TAG=7.1-apache
    - TAG=7.1-cli
    - TAG=7.1-fpm
    - TAG=7.2-apache
    - TAG=7.2-cli

before_script:
  - git submodule update --init
  - ./build.sh $TAG

script:
  - "[[ ! -x $TAG/test.sh ]] || $TAG/test.sh"
  # All container need to be able to restart
  - docker run pretzlaw/php:$TAG tail -f /dev/null
  - export RUN_COUNT="$(docker ps -q | wc -l)"
  - docker restart $(docker ps -q)
  - docker ps -a
  - "[[ \"$RUN_COUNT\" == \"$(docker ps -q | wc -l)\" ]]"
